<a href="https://colab.research.google.com/github/Anvith17/dsProject/blob/main/Day06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split


In [2]:
data =pd.read_csv('https://talentcocomedia.s3.amazonaws.com/ml-assets/heart-disease.csv')

In [3]:
y = data['target']

In [4]:
x = data.drop('target', axis =1)

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=4)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

((212, 13), (91, 13), (212,), (91,))

# Logistic Regression

In [6]:
from sklearn.linear_model import LogisticRegression
lr_model=LogisticRegression(penalty='l2', solver= 'newton-cg', C=5)

In [7]:
lr_model.fit(x_train,y_train)

LogisticRegression(C=5, solver='newton-cg')

In [8]:
y_pred_lr = lr_model.predict(x_test)
y_pred_lr

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1])

In [9]:
from sklearn.metrics import accuracy_score
acc_lr = accuracy_score(y_pred_lr, y_test)
acc_lr

0.8021978021978022

# KNeighborsClassifier

In [10]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [11]:
yPredKnn = neigh.predict(x_test)

In [12]:
yPredKnn

array([1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0])

Accuracy:

In [13]:
accKnn = accuracy_score(yPredKnn , y_test)

In [14]:
accKnn

0.6263736263736264

# Decisiontree Classifier

In [15]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [16]:
yPredDtc = dtc.predict(x_test)

In [17]:
yPredDtc

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1])

Accuracy:

In [18]:
accDtc = accuracy_score(yPredDtc , y_test)

In [19]:
accDtc

0.7032967032967034

In [21]:
val =list(np.arange(1,20,1))
val

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [22]:
from sklearn.model_selection import GridSearchCV

model_lr = LogisticRegression(penalty='l2')

parameters = {'solver':('newton-cg', 'liblinear', 'sag', 'saga'), 'C':val}

clf_lr = GridSearchCV(model_lr, parameters)
clf_lr.fit(x_train, y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means 

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
                               15, 16, 17, 18, 19],
                         'solver': ('newton-cg', 'liblinear', 'sag', 'saga')})

In [23]:
print(clf_lr.best_params_)

{'C': 3, 'solver': 'newton-cg'}


In [24]:
test_pred = clf_lr.predict(x_test)

In [25]:
acc_lr_gs = accuracy_score(test_pred, y_test)
acc_lr_gs

0.8021978021978022

# Confusion Matrix

In [26]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_pred,y_test)

array([[27,  7],
       [11, 46]])

In [27]:
from sklearn.metrics import classification_report

print(classification_report(y_test, test_pred))

              precision    recall  f1-score   support

           0       0.79      0.71      0.75        38
           1       0.81      0.87      0.84        53

    accuracy                           0.80        91
   macro avg       0.80      0.79      0.79        91
weighted avg       0.80      0.80      0.80        91

